### PR TITLE
Remove homepage/dashboard

### PR DESCRIPTION
**Pull request by abulte**
This removes the homepage/dashboard. It's very resource intensive on a big database (such as on data.gouv.fr — the server becomes unresponsive for many minutes when the page is generated) and we don't really use it (so investing in a new, more performant, version seems overkill). We can still use the CSV export for analysis purposes. We now also store some croquemort info in data.gouv.fr's database that can be used directly for quality/report purposes.

### CODE REVIEW

**Comment by davidbgk** [comment]
Instead of removing it, what about an option to disallow the route? Even if it's not pertinent for data.gouv I guess it can be useful for smaller projects?

**Comment by abulte** [comment]
@davidbgk True, that's a valid option. Do we know of any other project using it? I don't really want to maintain (or potentially maintain at least) some "dead" code just for the sake of it.

**Comment by davidbgk** [comment]
@abulte agreed, it's quite hard to guess without any feedback/reported issue…

**Comment by abulte** [comment]
Thanks @davidbgk! That was some epic code you wrote. I take comfort in knowing that it still lives in git history ❤️.

**Pull request merged**
